name: Enviar Formulário para Discord

on:
  push:
    branches:
      - main  # O fluxo de trabalho será acionado quando houver um push para a branch "main"

jobs:
  enviarFormulario:
    runs-on: ubuntu-latest  # Define o ambiente no qual o workflow será executado (Ubuntu, no caso)

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2  # Faz checkout do seu código-fonte do repositório

    - name: Enviar dados para o Discord via Webhook
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.webhook }}  # Usa o secret chamado "webhook" que você configurou
      run: |
        curl -X POST $DISCORD_WEBHOOK_URL \
          -H "Content-Type: application/json" \
          -d '{
                "embeds": [{
                    "title": "Novo Contato",
                    "description": "Nome: João\nEmail: joao@example.com\nMensagem: Olá, como posso ajudar?",
                    "color": 0x9e26d6
                }]
            }'